preset: symfony

finder:
  exclude:
    - "tests"

enabled:
  - ordered_use

disabled:
  - phpdoc_annotation_without_dot # This is still buggy: https://github.com/symfony/symfony/pull/19198
  - short_array_syntax # Support PHP 5
  - no_superfluous_phpdoc_tags_symfony # All params/return tags should be preserved
